In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import pandas as pd
from matplotlib.pylab import rcParams
rcParams['figure.figsize']=20,10
from keras.models import Sequential
from keras.layers import LSTM,Dropout,Dense
from sklearn.preprocessing import MinMaxScaler

In [2]:
X=[]
for i in range(4996):
    X.append(i)
X = np.array(X).reshape(-1,1)
X

array([[   0],
       [   1],
       [   2],
       ...,
       [4993],
       [4994],
       [4995]])

In [3]:
Y=pd.read_csv("C:/Users/DMD-7/Downloads/a.csv")
Y.values.tolist()
np.array(Y)
Y.shape

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/DMD-7/Downloads/a.csv'

In [ ]:
Y_train=Y[0:4996]
Y_train.shape

(4996, 1)

In [ ]:
lstm_model=Sequential()
lstm_model.add(LSTM(units=50,return_sequences=True,input_shape=(np.shape(X))))
lstm_model.add(LSTM(units=50))
lstm_model.add(Dense(1))
# model_data=data[len(data)-len(valid_data)-60:].values
# model_data=model_data.reshape(-1,1)
# model_data=scaler.transform(model_data)

In [ ]:
lstm_model.compile(loss="mean_squared_error",optimizer="adam")
lstm_model.fit(X,Y_train,epochs=10,batch_size=5)
X_test=[4996,4997,4998,4999]
X_test=np.array(X_test).reshape(-1,1)

# X_test=np.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

Epoch 1/10
1000/1000 [==============================] - 11s 8ms/step - loss: 6.8769
Epoch 2/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0892
Epoch 3/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0842
Epoch 4/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0795
Epoch 5/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0765
Epoch 6/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0746
Epoch 7/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0727
Epoch 8/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0715
Epoch 9/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0709
Epoch 10/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0696


In [ ]:
X_test

array([[4996],
       [4997],
       [4998],
       [4999]])

In [ ]:
predicted_y=lstm_model.predict(X_test)
predicted_y
# predicted_stock_price=scaler.inverse_transform(predicted_stock_price)

1/1 [==============================] - 0s 19ms/step


array([[7.901363],
       [7.901363],
       [7.901363],
       [7.901363]], dtype=float32)

In [ ]:
predicted_y= regsr.predict(to_predict_x)
m= regsr.coef_
c= regsr.intercept_
print("Predicted y:\n",predicted_y)
print("slope (m): ",m)
print("y-intercept (c): ",c)

Predicted y:
 [[7.53357815]
 [7.53344293]
 [7.5333077 ]
 [7.53317248]]
slope (m):  [[-0.00013522]]
y-intercept (c):  [8.20916017]
